export const vaultResolverAbi = [
  {
    type: "function",
    name: "getAllVaultsAddresses",
    inputs: [],
    outputs: [{ type: "address[]", name: "" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getVaultEntireData",
    inputs: [{ type: "address", name: "vault_" }],
    outputs: [
      {
        type: "tuple",
        name: "vaultData_",
        components: [
          { type: "address", name: "vault" },
          { type: "bool", name: "isSmartCol" },
          { type: "bool", name: "isSmartDebt" },
          {
            type: "tuple",
            name: "constantVariables",
            components: [
              { type: "address", name: "liquidity" },
              { type: "address", name: "factory" },
              { type: "address", name: "operateImplementation" },
              { type: "address", name: "adminImplementation" },
              { type: "address", name: "secondaryImplementation" },
              { type: "address", name: "deployer" },
              { type: "address", name: "supply" },
              { type: "address", name: "borrow" },
              {
                type: "tuple",
                name: "supplyToken",
                components: [
                  { type: "address", name: "token0" },
                  { type: "address", name: "token1" },
                ],
              },
              {
                type: "tuple",
                name: "borrowToken",
                components: [
                  { type: "address", name: "token0" },
                  { type: "address", name: "token1" },
                ],
              },
              { type: "uint256", name: "vaultId" },
              { type: "uint256", name: "vaultType" },
              { type: "bytes32", name: "supplyExchangePriceSlot" },
              { type: "bytes32", name: "borrowExchangePriceSlot" },
              { type: "bytes32", name: "userSupplySlot" },
              { type: "bytes32", name: "userBorrowSlot" },
            ],
          },
          {
            type: "tuple",
            name: "configs",
            components: [
              { type: "uint16", name: "supplyRateMagnifier" },
              { type: "uint16", name: "borrowRateMagnifier" },
              { type: "uint16", name: "collateralFactor" },
              { type: "uint16", name: "liquidationThreshold" },
              { type: "uint16", name: "liquidationMaxLimit" },
              { type: "uint16", name: "withdrawalGap" },
              { type: "uint16", name: "liquidationPenalty" },
              { type: "uint16", name: "borrowFee" },
              { type: "address", name: "oracle" },
              { type: "uint256", name: "oraclePriceOperate" },
              { type: "uint256", name: "oraclePriceLiquidate" },
              { type: "address", name: "rebalancer" },
              { type: "uint256", name: "lastUpdateTimestamp" },
            ],
          },
          {
            type: "tuple",
            name: "exchangePricesAndRates",
            components: [
              { type: "uint256", name: "lastStoredLiquiditySupplyExchangePrice" },
              { type: "uint256", name: "lastStoredLiquidityBorrowExchangePrice" },
              { type: "uint256", name: "lastStoredVaultSupplyExchangePrice" },
              { type: "uint256", name: "lastStoredVaultBorrowExchangePrice" },
              { type: "uint256", name: "liquiditySupplyExchangePrice" },
              { type: "uint256", name: "liquidityBorrowExchangePrice" },
              { type: "uint256", name: "vaultSupplyExchangePrice" },
              { type: "uint256", name: "vaultBorrowExchangePrice" },
              { type: "uint256", name: "supplyRateLiquidity" },
              { type: "uint256", name: "borrowRateLiquidity" },
              { type: "int256", name: "supplyRateVault" },
              { type: "int256", name: "borrowRateVault" },
              { type: "int256", name: "rewardsOrFeeRateSupply" },
              { type: "int256", name: "rewardsOrFeeRateBorrow" },
            ],
          },
          {
            type: "tuple",
            name: "totalSupplyAndBorrow",
            components: [
              { type: "uint256", name: "totalSupplyVault" },
              { type: "uint256", name: "totalBorrowVault" },
              { type: "uint256", name: "totalSupplyLiquidityOrDex" },
              { type: "uint256", name: "totalBorrowLiquidityOrDex" },
              { type: "uint256", name: "absorbedSupply" },
              { type: "uint256", name: "absorbedBorrow" },
            ],
          },
          {
            type: "tuple",
            name: "limitsAndAvailability",
            components: [
              { type: "uint256", name: "withdrawLimit" },
              { type: "uint256", name: "withdrawableUntilLimit" },
              { type: "uint256", name: "withdrawable" },
              { type: "uint256", name: "borrowLimit" },
              { type: "uint256", name: "borrowableUntilLimit" },
              { type: "uint256", name: "borrowable" },
              { type: "uint256", name: "borrowLimitUtilization" },
              { type: "uint256", name: "minimumBorrowing" },
            ],
          },
          {
            type: "tuple",
            name: "vaultState",
            components: [
              { type: "uint256", name: "totalPositions" },
              { type: "int256", name: "topTick" },
              { type: "uint256", name: "currentBranch" },
              { type: "uint256", name: "totalBranch" },
              { type: "uint256", name: "totalBorrow" },
              { type: "uint256", name: "totalSupply" },
              {
                type: "tuple",
                name: "currentBranchState",
                components: [
                  { type: "uint256", name: "status" },
                  { type: "int256", name: "minimaTick" },
                  { type: "uint256", name: "debtFactor" },
                  { type: "uint256", name: "partials" },
                  { type: "uint256", name: "debtLiquidity" },
                  { type: "uint256", name: "baseBranchId" },
                  { type: "int256", name: "baseBranchMinima" },
                ],
              },
            ],
          },
          {
            type: "tuple",
            name: "liquidityUserSupplyData",
            components: [
              { type: "bool", name: "modeWithInterest" },
              { type: "uint256", name: "supply" },
              { type: "uint256", name: "withdrawalLimit" },
              { type: "uint256", name: "lastUpdateTimestamp" },
              { type: "uint256", name: "expandPercent" },
              { type: "uint256", name: "expandDuration" },
              { type: "uint256", name: "baseWithdrawalLimit" },
              { type: "uint256", name: "withdrawableUntilLimit" },
              { type: "uint256", name: "withdrawable" },
              { type: "uint256", name: "decayEndTimestamp" },
              { type: "uint256", name: "decayAmount" },
            ],
          },
          {
            type: "tuple",
            name: "liquidityUserBorrowData",
            components: [
              { type: "bool", name: "modeWithInterest" },
              { type: "uint256", name: "borrow" },
              { type: "uint256", name: "borrowLimit" },
              { type: "uint256", name: "lastUpdateTimestamp" },
              { type: "uint256", name: "expandPercent" },
              { type: "uint256", name: "expandDuration" },
              { type: "uint256", name: "baseBorrowLimit" },
              { type: "uint256", name: "maxBorrowLimit" },
              { type: "uint256", name: "borrowableUntilLimit" },
              { type: "uint256", name: "borrowable" },
              { type: "uint256", name: "borrowLimitUtilization" },
            ],
          },
        ],
      },
    ],
    stateMutability: "view",
  },
] as const;

export const lendingResolverAbi = [
  {
    type: "function",
    name: "getAllFTokens",
    inputs: [],
    outputs: [{ type: "address[]", name: "" }],
    stateMutability: "view",
  },
] as const;

export const fTokenAbi = [
  {
    type: "function",
    name: "asset",
    inputs: [],
    outputs: [{ type: "address", name: "" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "symbol",
    inputs: [],
    outputs: [{ type: "string", name: "" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isNativeUnderlying",
    inputs: [],
    outputs: [{ type: "bool", name: "" }],
    stateMutability: "view",
  },
] as const;
